// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3b_DxqEQMcrgIxedc5EMP9l-8SWXiMC4',
    appId: '1:795677731634:web:8eac12793c65c594ad052b',
    messagingSenderId: '795677731634',
    projectId: 'v-kommerce',
    authDomain: 'v-kommerce.firebaseapp.com',
    storageBucket: 'v-kommerce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSNfoX3LpWcDxcxgonsxhD89nRq7aut8w',
    appId: '1:795677731634:android:f9530e375daef46bad052b',
    messagingSenderId: '795677731634',
    projectId: 'v-kommerce',
    storageBucket: 'v-kommerce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx_S7FNrCJX1vaW6KHyMg8vpmKKZkkOjk',
    appId: '1:795677731634:ios:c2de0b3506916dd1ad052b',
    messagingSenderId: '795677731634',
    projectId: 'v-kommerce',
    storageBucket: 'v-kommerce.firebasestorage.app',
    iosBundleId: 'com.example.vKommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx_S7FNrCJX1vaW6KHyMg8vpmKKZkkOjk',
    appId: '1:795677731634:ios:c2de0b3506916dd1ad052b',
    messagingSenderId: '795677731634',
    projectId: 'v-kommerce',
    storageBucket: 'v-kommerce.firebasestorage.app',
    iosBundleId: 'com.example.vKommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3b_DxqEQMcrgIxedc5EMP9l-8SWXiMC4',
    appId: '1:795677731634:web:ba8fb40c2c399972ad052b',
    messagingSenderId: '795677731634',
    projectId: 'v-kommerce',
    authDomain: 'v-kommerce.firebaseapp.com',
    storageBucket: 'v-kommerce.firebasestorage.app',
  );
}
